/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoInterdiciplinar.viwers;

import javax.swing.JTextArea;
import projetoInterdiciplinar.controler.ControllerCreditos;

/**
 *
 * @author Gabriel
 */
public class Creditos extends javax.swing.JInternalFrame {

    private final ControllerCreditos controller;
    
    public Creditos() {
        initComponents();
        this.controller = new ControllerCreditos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCreditos = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("Créditos");

        txtAreaCreditos.setEditable(false);
        txtAreaCreditos.setBackground(new java.awt.Color(51, 51, 51));
        txtAreaCreditos.setColumns(20);
        txtAreaCreditos.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtAreaCreditos.setForeground(new java.awt.Color(19, 163, 9));
        txtAreaCreditos.setLineWrap(true);
        txtAreaCreditos.setRows(5);
        txtAreaCreditos.setText("----------------------------- CRÈDITOs ------------------------------------\n\nCriado by Gabriel Pinheiro\n\nAgradecimentos:\n - A Deus, Porque dele, e por ele, e para ele são todas as coisas;\n\n - Professor Hugo, que apoiou para criação de toda a estruturação do código;\n\n - Professora Cristiane, por todo o conhecimento sobre o Java;\n\n - Meu Pai, minha inspiração e um exímio programador\n\n\n\n\n\"O que é o homem na natureza? Um nada em relação ao infinito, um tudo em relação ao nada, um ponto a meio entre nada e tudo\"_Blase Pascal");
        txtAreaCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAreaCreditosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtAreaCreditos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaCreditosMouseClicked
        
    }//GEN-LAST:event_txtAreaCreditosMouseClicked

    public JTextArea getTxtAreaCreditos() {
        return txtAreaCreditos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaCreditos;
    // End of variables declaration//GEN-END:variables
}
