
package projetoInterdiciplinar.viwers;


public class Sobre extends javax.swing.JInternalFrame {


    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Objetivo:\nEste programa foi desenvolvido com o objetivo de entrega do projeto           Interdisciplinar do Curso de ADS na faculdade Cruzeiro do Sul.\n\nFunções:\nEste programa dispões das seguintes funcionalidade: consultar banco de dados, adicionar produto ao banco, e edita-lo. Além de gerar um relatorio  contendo os itens com quantidade abaixo do mínimo desejado.\n\nSobre o Banco de Dados:\nAtravés da utilização de classes java para ler e escrever arquivos, foi           criado as classes loader e saver, em que respectivamente fazem leitura e escrita num arquivo na raiz da pasta (produtos.csv), onde guarda os dados\n\nSobre o desenvolvimento:\nEste programa foi desenvolvido em diversas fases, todo o progresso podeser acompanhado no GitHub (https://github.com/G4brIel-Sh4rp/ProjetoInterdisciplinar/commits/master). Obs.: Fora utilizado a estruturação de              programa MVC, essa foi a primeira aplicação feita nesta estrutura,  por        tanto haveria possíbilidade de algumas melhoras.\n\nAos avaliadores:\nO desenvolvimento deste programa foi realizado por um iniciante, por tantohá diversos fatores que poderiam ser melhorados em minha maneira de programar. Sendo assim por favor me informar se gostou e também           críticas sobre. E-mail: gabriel.pds2001@gmail.com");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
